# Generated by Django 4.0.5 on 2022-07-25 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('identity', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=300)),
                ('story', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='characters')),
                ('height', models.FloatField(null=True)),
                ('power', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
    ]
