# Generated by Django 4.0.5 on 2022-07-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='combat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.IntegerField(null=True),
        ),
    ]
